vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.wrap = false
vim.opt.expandtab = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.scrolloff = 999
vim.opt.virtualedit = "block"
vim.opt.ignorecase = true
vim.opt.termguicolors = true
vim.opt.signcolumn = "yes"
vim.opt.showmode = false
vim.opt.cursorline = true
vim.opt.laststatus = 3
-- vim.opt.inccommand = "split"
-- vim.opt.colorcolumn = "80"
-- vim.opt.clipboard = "unnamedplus"
-- vim.g.mapleader = " "
